# Generated by Django 6.0.1 on 2026-01-30 03:45

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_profile_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile/default.jpg', error_messages={'invalid': 'Image files only with maximum of 5 MB.'}, help_text='Max file size is 5 MB', null=True, upload_to='profile/', validators=[utils.validators.validate_file_size]),
        ),
    ]
